# This is a basic workflow to help you get started with Actions

name: Timer App

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    

    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: installing surge
        run: npm install --global surge
      - name: installing npm
        run: npm install  
      - name: installing Typescript
        run: npm install -g typescript
      - name: Testing
        run: npm run test  
      - name: running build
        run: npm run build
    # Runs a single command using the runners shell
      - name: deploying using surge
        run: surge ./build timer-by-waqas.surge.sh --token ${{ secrets.TIMER }}
